### ISSUE TITLE
Fill: click in space below to create new space at current level with same geometry

### ISSUE THREAD

**Issue by ajwinter** [NREL/openstudio-geometry-editor#10]
If the user enables viewing of previous-story geometry, then let them double click that geometry to create a space of the same geometry on the current story

**Comment by devKate** [comment]
This is going to conflict with existing mouse events. OL default behavior is to zoom in on double click. This also might not be great UX, because if the user is clicking to draw faces they could end up triggering this by accident. Maybe we want a separate tool for cloning geometry?

**Comment by shorowit** [comment]
A separate tool would be fine for now. I think it should be a "Fill" (or "Paint"?) tool. When a space is selected in the sidebar and you single click inside the geometry of a space from the story below, it would reuse that geometry. Would that work?

**Comment by devKate** [comment]
if the user clicks clone, what should happen if:
- no space/shading is selected
- geometry exists for the selected space/shading and does not intersect with the face to be cloned

**Comment by shorowit** [comment]
This is not working in the latest develop.

**Comment by shorowit** [comment]
Yay, it works again!
