### ISSUE TITLE
Undo/redo

### ISSUE THREAD

**Issue by ajwinter** [NREL/openstudio-geometry-editor#101]

**Comment by gh-23378** [comment]
Base functionality is there but I think that @macumber or @shorowit should test this and give feedback before we say it is done.

**Comment by shorowit** [comment]
- [x] Add buttons for undo/redo
- [x] Use ctrl-y instead of (or in addition to) ctrl-shift-z for redo
- [x] Display a message for what was just changed

**Comment by shorowit** [comment]
Looks good with my testing. A great feature!
