### ISSUE TITLE
Allow snapping to angles (vertical/horizontal)

### ISSUE THREAD

**Issue by ajwinter** [NREL/openstudio-geometry-editor#14]

**Comment by devKate** [comment]
Is this only going to be allowed when certain keys are held? It could conflict with other types of snapping.

**Comment by macumber** [comment]
Snapping logic should be discussed in this section: https://docs.google.com/document/d/1NrsPjshRdhiOFi7bNDe7-KmVijHOYlQ0A6l5kVsVpJg/edit#heading=h.uhk1fm5zz8ck

If there are corner cases or things wrong with the logic as documented please describe them in that document

**Comment by macumber** [comment]
I think the idea is to not require holding a special key to snap to horizontal or vertical, but if we dont like that we can look into only doing this snapping when holding shift
