### ISSUE TITLE
Consistent object naming scheme

### ISSUE THREAD

**Issue by ajwinter** [NREL/openstudio-geometry-editor#3]
Stories should be named incrementally (Story 1, Story 2, etc.), whereas Spaces should be unique.

Outstanding question: how unique do spaces need to be? It's an odd user experience to get a random number as it is currently, but it does solve having "Space 2" exist in multiple places (for example).

**Comment by macumber** [comment]
Especially important for stories, seeing "Story 56" seems weird for the second story

**Comment by ajwinter** [comment]
Partially fixed. Remaining task: make space names have the story in them, like so: Space 1-1, Space 1-2, for Story 1, then Space 2-1, Space 2-2, for Story 2, etc.
