### ISSUE TITLE
Display north axis

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#33]
- [ ] Synchonized North axis should be with map rotation
- [ ] Y -axis increases going up, positive Y direction is building north as shown here http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-simulation-parameters.html#building
- [ ] Set north axis in non-map mode
- [ ] Show north axis as an arrow in upper left corner pointing in direction of north in both map and non-map modes

**Comment by ajwinter** [comment]
In non-map mode, have a "North Axis" text field in the top bar that the user can input a number into to set rotation.
