### ISSUE TITLE
Opening floorplan should restore grid

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#44]
I drew the following square with a 50 m grid, then re-opened the file.  Now the shape does not match the grid.

![image](https://cloud.githubusercontent.com/assets/1327850/26419630/960b027e-407d-11e7-8707-c2f434e3f8e6.png)

**Comment by ajwinter** [comment]
The core issue is fixed (shapes not matching the grid), but there's an issue with the grid line and label sizes after importing. This same issue also happens when resizing the window after changing zoom level.
