### ISSUE TITLE
Editor gets confused when browser is zoomed in or out

### ISSUE THREAD

**Issue by ljbrackney** [NREL/openstudio-geometry-editor#47]
Cmd/Ctrl +/- zooming confuses the editor (at least in Chrome).  Geometry is no longer located correctly on map, cursor and geometry points aren't co-located, etc.

**Comment by ljbrackney** [comment]
This behavior is still present when the app is used within the OpenStudio App.  Both grid snap and labeling get out of whack when the App is resized or the pane bar is dragged.

![resize](https://user-images.githubusercontent.com/2230150/28372456-9b86c244-6c54-11e7-98dd-2e7058b59dfa.png)

**Comment by macumber** [comment]
Does the refresh button work to fix this?

**Comment by ljbrackney** [comment]
Currently the refresh button wipes everything out and returns me to the quick start dialog.

**Comment by shorowit** [comment]
A colleague keeps browser zooming out of habit. Would it be possible to disable the browser zoom?

**Comment by bgschiller** [comment]
@shorowit It looks like it's not something we have access to in js: https://stackoverflow.com/questions/23639813/how-to-prevent-a-user-from-using-ctrl-to-zoom

There might be an extension one can install to disable that behavior, but I didn't find anything solid in googling for it.

**Comment by shorowit** [comment]
I can no longer reproduce any of the reported issues ("Geometry is no longer located correctly on map, cursor and geometry points aren't co-located, etc.") using the standalone tool in chrome. 🥇 

@ljbrackney please open this back up if you see anything weird.
