### ISSUE TITLE
Space disappears when drawing another

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-geometry-editor#49]
I create the first space using several rectangles, to create a L shape.

![screen shot 2017-05-30 at 11 15 39 am](https://cloud.githubusercontent.com/assets/5479063/26576534/8150dbc8-4529-11e7-805d-e2c96f2351a5.png)

Then I click on "New Space", and draw the missing rectangle next to the L to create a full rectangle. Space 1 disapears, cannot find it anywhere.

![screen shot 2017-05-30 at 11 15 52 am](https://cloud.githubusercontent.com/assets/5479063/26576570/9d756878-4529-11e7-9400-d5741dc582df.png)

**Comment by ljbrackney** [comment]
Verified.
