### ISSUE TITLE
Select mode bugs

### ISSUE THREAD

**Issue by shorowit** [NREL/openstudio-geometry-editor#52]
These occur when you have the Select button clicked:
- If you have two spaces drawn, and space 1 is selected, and then you click on space 2, space 1 is deselected. If you click again, then space 2 finally becomes selected. The deselection step should not occur.
- If you click off in space (not on a space), the selected space becomes deselected. Rather, I think nothing should happen (the selected space should remain selected).
- You can (but should not be able to) select spaces that appear from the previous story.

**Comment by devKate** [comment]
Just want to double check that clicking off of a face on empty grid space shouldn't result in deselection. I think there was some confusion over that before.
