### ISSUE TITLE
faces can be divided during clipping operations

### ISSUE THREAD

**Issue by devKate** [NREL/openstudio-geometry-editor#55]
Currently, if a clipper operation results in two closed faces, we discard one and save whichever face happened to be returned first from clipper

**Comment by macumber** [comment]
If the operation is correct that there are two or more faces in the result then the design was to revert the operation, this would be something like drawing a space that cuts through another space, it is not allowed. 

However, there may be cases where the result does not really have two polygons.  I'd especially watch out for the case where you get multiple faces in the result but some of those faces have zero area.  So you might want to prune out bad results before deciding if the result failed.
