### ISSUE TITLE
Snapping distance should never be >= grid spacing

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#60]
If the snapping distance is greater than or equal to the grid spacing then you can get into situations where you cannot place a point at a grid point since it is snapping to a point on an adjacent grid

**Comment by macumber** [comment]
Can place here:
![image](https://user-images.githubusercontent.com/1327850/26993334-dcfd37b6-4d1f-11e7-95f6-4ef3c6120d3b.png)

Can't place here:
![image](https://user-images.githubusercontent.com/1327850/26993340-e147cd5e-4d1f-11e7-9a0e-e81dfd448d21.png)

Can place here:
![image](https://user-images.githubusercontent.com/1327850/26993346-e619f5be-4d1f-11e7-8dcc-f9d8343f7379.png)

**Comment by ljbrackney** [comment]
This may be related - although I have the grid off in my case.  When using the rectangle tool I've noticed that the final space geometry and placement sometimes changes after I finish specifying the geometry.  Here's one example:

![snap](https://user-images.githubusercontent.com/2230150/27089923-9f60fb10-5010-11e7-8fe0-be9fdefd66de.png)

I've also seen this when adding additional rectangles.  The space shifts and no longer intersects the adjacent space.
