### ISSUE TITLE
Simple floorplan.json will not import via measure

### ISSUE THREAD

**Issue by ljbrackney** [NREL/openstudio-geometry-editor#63]
Attempting to create extremely simple geometry with all data defined, and the floorplan.json will not import into the App.  Current json attached...

[floorplan.json.zip](https://github.com/NREL/openstudio-geometry-editor/files/1071971/floorplan.json.zip)

**Comment by macumber** [comment]
Are you getting this message from the measure:

runner.registerError("Cannot find floorplan path '#{floorplan_path}'.")

Attached is the file I get

[floorplan.osm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1073403/floorplan.osm.txt)

Have you tried entering the full path to the file as the measure argument?

**Comment by ljbrackney** [comment]
I do enter the full path. I'm not getting the file path error. The measure reports success but nothing is pulled in.

On Jun 13, 2017, at 8:14 PM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you getting this message from the measure:

runner.registerError("Cannot find floorplan path '#{floorplan_path}'.")

Attached is the file I get

floorplan.osm.txt<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2Fopenstudio-geometry-editor%2Ffiles%2F1073403%2Ffloorplan.osm.txt&data=02%7C01%7Clarry.brackney%40nrel.gov%7C108c431ed806485834c008d4b2d358b1%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636330068179011755&sdata=7%2FbCVJZbvxp9cRZ7sk5RBI70lAwiac6hLdD6ucKmWdA%3D&reserved=0>

Have you tried entering the full path to the file as the measure argument?

-

**Comment by macumber** [comment]
Updated measure, works in Apply Measure Now 

[measure.rb.txt](https://github.com/NREL/openstudio-geometry-editor/files/1073433/measure.rb.txt)
