### ISSUE TITLE
Vertex merging and clipper offset are changing geometry positions during storage

### ISSUE THREAD

**Issue by devKate** [NREL/openstudio-geometry-editor#66]
When points created by a clipper operation, dragging, or inferred points created by the rectangle tool are near saved vertices, the data store will merge them to prevent duplicate geometry. This can cause geometry to move around in potentially undesirable ways. We may want to adjust the tolerance for vertex merging or add a visual indicator to the rectangle tool when an inferred vertex will be merged.
<img width="398" alt="screen shot 2017-06-13 at 2 38 55 pm" src="https://user-images.githubusercontent.com/8015883/27105316-5695ebe8-504c-11e7-9b5a-2d1fdffcc441.png">

**Comment by ljbrackney** [comment]
That's what I noticed earlier. Thanks!

On Jun 13, 2017, at 2:24 PM, Katie Noland <notifications@github.com<mailto:notifications@github.com>> wrote:


When points created by a clipper operation, dragging, or inferred points created by the rectangle tool are near saved vertices, the data store will merge them to prevent duplicate geometry. This can cause geometry to move around in potentially undesirable ways.
[screen shot 2017-06-13 at 2 38 55 pm]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8015883%2F27105316-5695ebe8-504c-11e7-9b5a-2d1fdffcc441.png&data=02%7C01%7Clarry.brackney%40nrel.gov%7C5b538927b0204ab3fb6808d4b2a28deb%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636329858609932347&sdata=u0toyl4CrzgaranugyugafA8BNhVLSYq%2FcJqDBOYOiw%3D&reserved=0>

-
