### ISSUE TITLE
Test locked down grid mode

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#74]
We are considering adding a locked down grid mode (more similar to BeOpt).  We can test this mode without implementing it by doing the following:

- Do not use polygon mode, only draw rectangles
- Only set grid spacing to multiples of some common factor (e.g. 1ft, 2ft, 4ft, 8ft)
- Only start or end rectangles on grid points

**Comment by shorowit** [comment]
In retrospect, it seems like polygons would be supported just fine. You would only be able to snap to polygon vertices (or, really, the grid points they lay on); you wouldn't be able to snap along the edge of a polygon just as you can't snap along the edge of a rectangle. 

For example, you could still easily do this (all polygon vertices are on grid points):
![image](https://user-images.githubusercontent.com/5861765/27399921-a6e2f3c2-567b-11e7-92ef-38c81f90018a.png)

Or am I thinking about this wrong?

**Comment by shorowit** [comment]
Suggestions for first pass:
- Add a UI control to switch between locked down and standard grid modes
- Standard grid mode behaves as it does now
- Two changes are made for locked down mode:
  - Disable logic that allows snapping to edges
  - Remove ability to use shift for free-form drawing

Sound good @macumber?

**Comment by macumber** [comment]
Yup sounds good to me, I would be a little more specific that in grid mode you can only place vertices at a grid point.  Changing the grid after placing vertices does not affect previously placed vertices right?

**Comment by shorowit** [comment]
Correct, changing the grid after placing vertices does not affect previously placed vertices. But I was thinking we should continue to allow snapping to vertices (not just grid points) for that very situation.

**Comment by macumber** [comment]
Ah ok, so you can snap to grid points or vertices, makes sense.  I'm curious to give it a try.

**Comment by bgschiller** [comment]
@macumber @shorowit this is now available in develop.

**Comment by macumber** [comment]
How do we test this?  I don't see a button or config option to turn it on or off

**Comment by shorowit** [comment]
Shows up for me in the standalone_geometry_editor
![image](https://user-images.githubusercontent.com/5861765/29547976-ac9c8110-86ba-11e7-857f-890e7b5b698f.png)

**Comment by macumber** [comment]
I just rebuilt and updated dependencies and now am seeing this too.  I guess that the build must have failed with outdated dependencies before.  Thanks @shorowit !

**Comment by macumber** [comment]
Would have been nice for the build failure to be a little more explicit

**Comment by macumber** [comment]
FYI @ljbrackney we put this in for A/B testing.  The idea is to try it out with grid snapping only and with edge snapping also to figure out which we like better.

**Comment by macumber** [comment]
It might be possible to cut down some effort if we can live with grid snapping only.

**Comment by shorowit** [comment]
This is included by default in the latest versions.
