### ISSUE TITLE
Story pane UI

### ISSUE THREAD

**Issue by shorowit** [NREL/openstudio-geometry-editor#76]
The pane currently looks like this:
![image](https://user-images.githubusercontent.com/5861765/27398429-f5513014-5676-11e7-84a1-5d888ca79b3e.png)

I recommend small changes to make it look like this:
![image](https://user-images.githubusercontent.com/5861765/27398768-028f1d3a-5678-11e7-8c4e-7bc7998c6389.png)

**Comment by ljbrackney** [comment]
+1

**Comment by shorowit** [comment]
There will be a new proposal as part of #130
