### ISSUE TITLE
Prioritize name column in bottom pane

### ISSUE THREAD

**Issue by shorowit** [NREL/openstudio-geometry-editor#80]
If you have, e.g., Space selected as the Type, the first column should show space Names, not IDs. Same for other object types.

**Comment by macumber** [comment]
Let's make this a larger ticket for addressing columns in the lower grid:

- [ ]  Do not show ID or type columns for any object, they are not useful to the user
- [ ]  When creating first object of type, do not create additional columns after rename (currently type column is added after object is named)
- [x]  Reduce name complexity requirement to single character, name cannot be empty.  We should enforce unique names within a type
- [x]  Remove daylighting controls from Space in library
- [x]  Remove windows from story in library
- [x]  Add above_ceiling_plenum_height to story

**Comment by bgschiller** [comment]
@macumber What do you mean by the 'type' column? Do you mean 'Space Type', which appears only for spaces?
