### ISSUE TITLE
Image drag not working

### ISSUE THREAD

**Issue by ljbrackney** [NREL/openstudio-geometry-editor#82]
Image file attached along with screenshot of editor.  My hope is that I could overlay this on the La Kretz Innovation campus map view for scaling and orientation, then trace over it.

![lakretz](https://user-images.githubusercontent.com/2230150/27705262-38dcc4a0-5cc2-11e7-8d41-65567122491d.jpg)

![image](https://user-images.githubusercontent.com/2230150/27705269-3caa977e-5cc2-11e7-98ad-09f7045abd0a.png)

**Comment by ljbrackney** [comment]
Also dragging of the image does not appear to be working.  Drag/resize is ignored and green rectangle consistently shows up as shown below.

![image2](https://user-images.githubusercontent.com/2230150/27705876-3ec193b2-5cc4-11e7-91bb-30d80e4b4d90.png)

**Comment by ljbrackney** [comment]
I have tried this with both JPG and PNG image file formats.

**Comment by ljbrackney** [comment]
I rebuilt this morning, and was able to get an image pulled in and resized it.  The drag behavior is still not working - the image wants to stay towards the bottom of the screen as before.  Trying to drag it to the upper part of the screen sometimes causes it to disappear altogether.

**Comment by ljbrackney** [comment]
Also the drag button gets stuck to selected and can't be unselected.  Switching to another view then back to image unselects it.

**Comment by ljbrackney** [comment]
I've played with this a bit more and will try to explain the behavior I'm seeing as best I can.

When I attempt to drag the image on top of the building, it snaps to a weird location (as shown in the last figure above).  When I change the image's size, it then magically appears at the place I originally dragged it to.  Try dragging it again and - poof back to the magic snap spot.  So I have to drag, resize, drag, resize, etc. until I have it where I want and at the size I want.

**Comment by ljbrackney** [comment]
Drag and resize is now working properly.  Image sizing box does not disappear when switching to Pan or another editor.

![image](https://user-images.githubusercontent.com/2230150/28803351-b2be5fec-7610-11e7-9aeb-dce1943414c0.png)

**Comment by ljbrackney** [comment]
Saving JSON with an image included fails.  Deleting image allows save to proceed.

**Comment by shorowit** [comment]
> Image sizing box does not disappear when switching to Pan or another editor.

This is still an issue in the latest develop.

**Comment by shorowit** [comment]
Looks good!
