### ISSUE TITLE
Only geometry and spaces translated by import floorplan measure

### ISSUE THREAD

**Issue by ljbrackney** [NREL/openstudio-geometry-editor#88]
Editor view:
![editor](https://user-images.githubusercontent.com/2230150/27888951-03fa72a6-619e-11e7-9cef-16292a947390.png)

Import and spaces look okay after import, but...

Loads tab:
![loads](https://user-images.githubusercontent.com/2230150/27889034-8d956462-619e-11e7-9a16-876a29303382.png)

Spaces tab:
![spaces](https://user-images.githubusercontent.com/2230150/27889037-93c3991c-619e-11e7-90de-6214e0f17700.png)

Zone view in app:
![osapp](https://user-images.githubusercontent.com/2230150/27888955-0daa6482-619e-11e7-899c-ad50d4f3ff21.png)

JSON:
[floorplan_2.json.zip](https://github.com/NREL/openstudio-geometry-editor/files/1126311/floorplan_2.json.zip)

**Comment by ljbrackney** [comment]
OSM after import:
[Blank.osm.zip](https://github.com/NREL/openstudio-geometry-editor/files/1126316/Blank.osm.zip)

**Comment by macumber** [comment]
Yeah that is known, I haven't done that stuff yet.  That's why the bulk of the work on merging is yet to be done.

**Comment by macumber** [comment]
Closing here, can re-open in OpenStudio issues for specific other objects
