### ISSUE TITLE
Y axis labels not visible

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#90]
I can see the X axis labels, but not the Y axis ones

**Comment by macumber** [comment]
![image](https://user-images.githubusercontent.com/1327850/27894076-413bed9c-61c7-11e7-947c-e153e4b53b7f.png)

**Comment by shorowit** [comment]
Looks like this was addressed? I'm seeing y-axis labels:

![image](https://user-images.githubusercontent.com/5861765/27929022-97aa8828-624e-11e7-9051-84bfef01e2cf.png)
