### ISSUE TITLE
Need zoom to fit

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-geometry-editor#91]
We should have a zoom to fit button that will zoom the current view to fit all geometry on the current story.  This should be called when opening an existing file.

**Comment by shorowit** [comment]
It would be nice to add small zoom in/out/fit buttons to a corner of the grid.

**Comment by DavidGoldwasser** [comment]
I was able to use + and _ to zoom when setting up map, but once I'm drawing spaces I can only use the scroll wheel, which isn't ideal on laptop. A agree zoom in out buttons or letting + - keys work would be nice.

**Comment by shorowit** [comment]
@bgschiller This has been implemented now, right?

**Comment by bgschiller** [comment]
@shorowit yep, c'est fini!
